import { INodeProperties } from "n8n-workflow";

export const createDrawingAppElementDescription: INodeProperties[] = [
	{
		displayName: 'JSON Content-Type',
		name: 'jsonContentType',
		description: 'JSON Content-Type',
		type: 'options',
		default: 'application/json;charset=UTF-8; qs=0.09',
		displayOptions: {
			show: {
				resource: [
					'Drawing',
				],
				operation: [
					'POST /api/drawings/create',
				],
			},
		},
		options: [
			{
				name: 'application/json;charset=UTF-8; qs=0.09',
				value: 'application/json;charset=UTF-8; qs=0.09',
			},
			{
				name: 'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
				value: 'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
			},
			{
				name: 'application/vnd.onshape.v1+json;charset=UTF-8;qs=0.1',
				value: 'application/vnd.onshape.v1+json;charset=UTF-8;qs=0.1',
			},
		],
	},
	{
		displayName: 'JSON Parameters',
		name: 'jsonParameters',
		description: 'jsonParameters - boolean',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: [
					'Drawing',
				],
				operation: [
					'POST /api/drawings/create',
				],
				jsonContentType: [
					'application/json;charset=UTF-8; qs=0.09',
					'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
					'application/vnd.onshape.v1+json;charset=UTF-8;qs=0.1',
				],
			},
		},
	},
	{
		displayName: 'JSON Object',
		name: 'jsonObject1-object (body)',
		description: 'jsonObject - collection',
		type: 'collection',
		default: {},
		placeholder: 'Add Field',
		typeOptions: {
			alwaysOpenEditWindow: true,
		},
		displayOptions: {
			show: {
				resource: [
					'Drawing',
				],
				operation: [
					'POST /api/drawings/create',
				],
				jsonParameters: [
					false,
				],
				jsonContentType: [
					'application/json;charset=UTF-8; qs=0.09',
					'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
					'application/vnd.onshape.v1+json;charset=UTF-8;qs=0.1',
				],
			},
		},
		options: [
			{
				name: 'modelType',
				displayName: 'modelType',
				description: 'modelType - string',
				type: 'string',
				default: '',
			},
			{
				name: 'templateVersionId',
				displayName: 'templateVersionId',
				description: 'templateVersionId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'units',
				displayName: 'units',
				description: 'units - string',
				type: 'string',
				default: '',
			},
			{
				name: 'decimalSeparator',
				displayName: 'decimalSeparator',
				description: 'decimalSeparator - string',
				type: 'string',
				default: '',
			},
			{
				name: 'revision',
				displayName: 'revision',
				description: 'revision - string',
				type: 'string',
				default: '',
			},
			{
				name: 'partNumber',
				displayName: 'partNumber',
				description: 'partNumber - string',
				type: 'string',
				default: '',
			},
			{
				name: 'workspaceId',
				displayName: 'workspaceId',
				description: 'workspaceId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'elementId',
				displayName: 'elementId',
				description: 'elementId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'documentId',
				displayName: 'documentId',
				description: 'documentId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'partId',
				displayName: 'partId',
				description: 'partId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'partQuery',
				displayName: 'partQuery',
				description: 'partQuery - string',
				type: 'string',
				default: '',
			},
			{
				name: 'elementMicroversionId',
				displayName: 'elementMicroversionId',
				description: 'elementMicroversionId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'externalDocumentId',
				displayName: 'externalDocumentId',
				description: 'externalDocumentId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'externalDocumentVersionId',
				displayName: 'externalDocumentVersionId',
				description: 'externalDocumentVersionId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'elementConfiguration',
				displayName: 'elementConfiguration',
				description: 'elementConfiguration - string',
				type: 'string',
				default: '',
			},
			{
				name: 'templateDocumentId',
				displayName: 'templateDocumentId',
				description: 'templateDocumentId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'templateWorkspaceId',
				displayName: 'templateWorkspaceId',
				description: 'templateWorkspaceId - string',
				type: 'string',
				default: '',
			},
			{
				displayName: 'templateArgs',
				name: 'templateArgs',
				description: 'templateArgs - array',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
				},
				default: '',
				options: [
					{
						displayName: 'templateArgsProperties',
						name: 'templateArgsProperties',
						values: [
							{
								name: 'templateArgs',
								displayName: 'templateArgs',
								description: 'templateArgs - string',
								type: 'string',
								default: '',
							},
						],
					},
				],
			},
			{
				name: 'templateElementId',
				displayName: 'templateElementId',
				description: 'templateElementId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'drawingName',
				displayName: 'drawingName',
				description: 'drawingName - string',
				type: 'string',
				default: '',
			},
			{
				name: 'projection',
				displayName: 'projection',
				description: 'projection - string',
				type: 'string',
				default: '',
			},
			{
				name: 'standard',
				displayName: 'standard',
				description: 'standard - string',
				type: 'string',
				default: '',
			},
			{
				name: 'border',
				displayName: 'border',
				description: 'border - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'titleblock',
				displayName: 'titleblock',
				description: 'titleblock - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'numberHorizontalZones',
				displayName: 'numberHorizontalZones',
				description: 'numberHorizontalZones - integer',
				type: 'number',
				default: 0,
			},
			{
				name: 'numberVerticalZones',
				displayName: 'numberVerticalZones',
				description: 'numberVerticalZones - integer',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'sketchIds',
				name: 'sketchIds',
				description: 'sketchIds - array',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
				},
				default: '',
				options: [
					{
						displayName: 'sketchIdsProperties',
						name: 'sketchIdsProperties',
						values: [
							{
								name: 'sketchIds',
								displayName: 'sketchIds',
								description: 'sketchIds - string',
								type: 'string',
								default: '',
							},
						],
					},
				],
			},
			{
				name: 'documentMicroversionId',
				displayName: 'documentMicroversionId',
				description: 'documentMicroversionId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'views',
				displayName: 'views',
				description: 'views - string',
				type: 'string',
				default: '',
			},
			{
				name: 'computeIntersection',
				displayName: 'computeIntersection',
				description: 'computeIntersection - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'qualityOption',
				displayName: 'qualityOption',
				description: 'qualityOption - string',
				type: 'string',
				default: '',
			},
			{
				name: 'simplificationOption',
				displayName: 'simplificationOption',
				description: 'simplificationOption - string',
				type: 'string',
				default: '',
			},
			{
				name: 'simplificationThreshold',
				displayName: 'simplificationThreshold',
				description: 'simplificationThreshold - number',
				type: 'number',
				default: '',
			},
			{
				name: 'showCutGeomOnly',
				displayName: 'showCutGeomOnly',
				description: 'showCutGeomOnly - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeSurfaces',
				displayName: 'includeSurfaces',
				description: 'includeSurfaces - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeWires',
				displayName: 'includeWires',
				description: 'includeWires - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'hiddenLines',
				displayName: 'hiddenLines',
				description: 'hiddenLines - string',
				type: 'string',
				default: '',
			},
			{
				name: 'isSurface',
				displayName: 'isSurface',
				description: 'isSurface - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'pureSketch',
				displayName: 'pureSketch',
				description: 'pureSketch - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'isSketchOnly',
				displayName: 'isSketchOnly',
				description: 'isSketchOnly - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'startZones',
				displayName: 'startZones',
				description: 'startZones - string',
				type: 'string',
				default: '',
			},
			{
				name: 'isFlattenedPart',
				displayName: 'isFlattenedPart',
				description: 'isFlattenedPart - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'referenceTypeEnum',
				displayName: 'referenceTypeEnum',
				description: 'referenceTypeEnum - string',
				type: 'string',
				default: '',
			},
			{
				name: 'referenceType',
				displayName: 'referenceType',
				description: 'referenceType - integer',
				type: 'number',
				default: 0,
			},
			{
				name: 'templateName',
				displayName: 'templateName',
				description: 'templateName - string',
				type: 'string',
				default: '',
			},
			{
				displayName: 'location',
				name: 'location',
				description: 'location - object',
				type: 'collection',
				default: '',
				placeholder: 'Add Field',
				options: [
					{
						name: 'groupId',
						displayName: 'groupId',
						description: 'groupId - string',
						type: 'string',
						default: '',
					},
					{
						name: 'position',
						displayName: 'position',
						description: 'position - integer',
						type: 'number',
						default: 0,
					},
					{
						name: 'elementId',
						displayName: 'elementId',
						description: 'elementId - string',
						type: 'string',
						default: '',
					},
				],
			},
			{
				name: 'size',
				displayName: 'size',
				description: 'size - string',
				type: 'string',
				default: '',
			},
			{
				name: 'language',
				displayName: 'language',
				description: 'language - string',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'JSON Object',
		name: 'jsonObject2-json(body)',
		description: 'jsonObject - json',
		type: 'json',
		default: '',
		typeOptions: {
			alwaysOpenEditWindow: true,
		},
		displayOptions: {
			show: {
				resource: [
					'Drawing',
				],
				operation: [
					'POST /api/drawings/create',
				],
				jsonParameters: [
					true,
				],
				jsonContentType: [
					'application/json;charset=UTF-8; qs=0.09',
					'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
					'application/vnd.onshape.v1+json;charset=UTF-8;qs=0.1',
				],
			},
		},
	},
];
