import { INodeProperties } from "n8n-workflow";

export const export2JsonDescription: INodeProperties[] = [
	{
		name: 'did-string(path)',
		displayName: 'did',
		description: 'did - string (path)',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
			},
		},
	},
	{
		name: 'wv-string(path)',
		displayName: 'wv',
		description: 'wv - string (path)',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
			},
		},
	},
	{
		name: 'wvid-string(path)',
		displayName: 'wvid',
		description: 'wvid - string (path)',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
			},
		},
	},
	{
		name: 'eid-string(path)',
		displayName: 'eid',
		description: 'eid - string (path)',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
			},
		},
	},
	{
		displayName: 'JSON Content-Type',
		name: 'jsonContentType',
		description: 'JSON Content-Type',
		type: 'options',
		default: 'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
			},
		},
		options: [
			{
				name: 'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
				value: 'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
			},
		],
	},
	{
		displayName: 'JSON Parameters',
		name: 'jsonParameters',
		description: 'jsonParameters - boolean',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
				jsonContentType: [
					'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
				],
			},
		},
	},
	{
		displayName: 'JSON Object',
		name: 'jsonObject1-object (body)',
		description: 'jsonObject - collection',
		type: 'collection',
		default: {},
		placeholder: 'Add Field',
		typeOptions: {
			alwaysOpenEditWindow: true,
		},
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
				jsonParameters: [
					false,
				],
				jsonContentType: [
					'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
				],
			},
		},
		options: [
			{
				name: 'angleTolerance',
				displayName: 'angleTolerance',
				description: 'angleTolerance - number',
				type: 'number',
				default: '',
			},
			{
				name: 'batchFlatPatterns',
				displayName: 'batchFlatPatterns',
				description: 'batchFlatPatterns - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'chordTolerance',
				displayName: 'chordTolerance',
				description: 'chordTolerance - number',
				type: 'number',
				default: '',
			},
			{
				name: 'cloudObjectId',
				displayName: 'cloudObjectId',
				description: 'cloudObjectId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'cloudStorageAccountId',
				displayName: 'cloudStorageAccountId',
				description: 'cloudStorageAccountId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'configuration',
				displayName: 'configuration',
				description: 'configuration - string',
				type: 'string',
				default: '',
			},
			{
				name: 'deepSearchForForeignData',
				displayName: 'deepSearchForForeignData',
				description: 'deepSearchForForeignData - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'destinationName',
				displayName: 'destinationName',
				description: 'destinationName - string',
				type: 'string',
				default: '',
			},
			{
				name: 'documentId',
				displayName: 'documentId',
				description: 'documentId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'documentVersionId',
				displayName: 'documentVersionId',
				description: 'documentVersionId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'elementId',
				displayName: 'elementId',
				description: 'elementId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'elementIds',
				displayName: 'elementIds',
				description: 'elementIds - string',
				type: 'string',
				default: '',
			},
			{
				name: 'emailLink',
				displayName: 'emailLink',
				description: 'emailLink - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'emailMessage',
				displayName: 'emailMessage',
				description: 'emailMessage - string',
				type: 'string',
				default: '',
			},
			{
				name: 'emailSubject',
				displayName: 'emailSubject',
				description: 'emailSubject - string',
				type: 'string',
				default: '',
			},
			{
				name: 'emailTo',
				displayName: 'emailTo',
				description: 'emailTo - string',
				type: 'string',
				default: '',
			},
			{
				name: 'extractToS3',
				displayName: 'extractToS3',
				description: 'extractToS3 - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'featureIds',
				displayName: 'featureIds',
				description: 'featureIds - string',
				type: 'string',
				default: '',
			},
			{
				name: 'flatten',
				displayName: 'flatten',
				description: 'flatten - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'format',
				displayName: 'format',
				description: 'format - string',
				type: 'string',
				default: '',
			},
			{
				name: 'fromUserId',
				displayName: 'fromUserId',
				description: 'fromUserId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'grouping',
				displayName: 'grouping',
				description: 'grouping - string',
				type: 'string',
				default: '',
			},
			{
				name: 'includeBendCenterlines',
				displayName: 'includeBendCenterlines',
				description: 'includeBendCenterlines - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeBendLines',
				displayName: 'includeBendLines',
				description: 'includeBendLines - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeComments',
				displayName: 'includeComments',
				description: 'includeComments - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeContentCaptures',
				displayName: 'includeContentCaptures',
				description: 'includeContentCaptures - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeCustomPropertiesData',
				displayName: 'includeCustomPropertiesData',
				description: 'includeCustomPropertiesData - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeExportIds',
				displayName: 'includeExportIds',
				description: 'includeExportIds - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeForeignData',
				displayName: 'includeForeignData',
				description: 'includeForeignData - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeItemsData',
				displayName: 'includeItemsData',
				description: 'includeItemsData - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeLinkedDocuments',
				displayName: 'includeLinkedDocuments',
				description: 'includeLinkedDocuments - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeReleaseManagementData',
				displayName: 'includeReleaseManagementData',
				description: 'includeReleaseManagementData - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeSketches',
				displayName: 'includeSketches',
				description: 'includeSketches - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeStd',
				displayName: 'includeStd',
				description: 'includeStd - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'includeThumbnails',
				displayName: 'includeThumbnails',
				description: 'includeThumbnails - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'isPartingOut',
				displayName: 'isPartingOut',
				description: 'isPartingOut - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'linkDocumentId',
				displayName: 'linkDocumentId',
				description: 'linkDocumentId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'linkDocumentWorkspaceId',
				displayName: 'linkDocumentWorkspaceId',
				description: 'linkDocumentWorkspaceId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'linkedDocumentSubSetId',
				displayName: 'linkedDocumentSubSetId',
				description: 'linkedDocumentSubSetId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'maxFacetWidth',
				displayName: 'maxFacetWidth',
				description: 'maxFacetWidth - number',
				type: 'number',
				default: '',
			},
			{
				name: 'microversion',
				displayName: 'microversion',
				description: 'microversion - string',
				type: 'string',
				default: '',
			},
			{
				name: 'minFacetWidth',
				displayName: 'minFacetWidth',
				description: 'minFacetWidth - number',
				type: 'number',
				default: '',
			},
			{
				name: 'mode',
				displayName: 'mode',
				description: 'mode - string',
				type: 'string',
				default: '',
			},
			{
				name: 'partIds',
				displayName: 'partIds',
				description: 'partIds - string',
				type: 'string',
				default: '',
			},
			{
				name: 'partQuery',
				displayName: 'partQuery',
				description: 'partQuery - string',
				type: 'string',
				default: '',
			},
			{
				name: 'password',
				displayName: 'password',
				description: 'password - string',
				type: 'string',
				default: '',
			},
			{
				name: 'passwordRequired',
				displayName: 'passwordRequired',
				description: 'passwordRequired - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'resolution',
				displayName: 'resolution',
				description: 'resolution - string',
				type: 'string',
				default: '',
			},
			{
				name: 'scale',
				displayName: 'scale',
				description: 'scale - number',
				type: 'number',
				default: '',
			},
			{
				name: 'sendCopyToMe',
				displayName: 'sendCopyToMe',
				description: 'sendCopyToMe - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'sheetMetalFlat',
				displayName: 'sheetMetalFlat',
				description: 'sheetMetalFlat - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'splinesAsPolylines',
				displayName: 'splinesAsPolylines',
				description: 'splinesAsPolylines - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'storeInDocument',
				displayName: 'storeInDocument',
				description: 'storeInDocument - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'triggerAutoDownload',
				displayName: 'triggerAutoDownload',
				description: 'triggerAutoDownload - boolean',
				type: 'boolean',
				default: false,
			},
			{
				name: 'units',
				displayName: 'units',
				description: 'units - string',
				type: 'string',
				default: '',
			},
			{
				name: 'userId',
				displayName: 'userId',
				description: 'userId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'validForDays',
				displayName: 'validForDays',
				description: 'validForDays - integer',
				type: 'number',
				default: 0,
			},
			{
				name: 'version',
				displayName: 'version',
				description: 'version - string',
				type: 'string',
				default: '',
			},
			{
				name: 'view',
				displayName: 'view',
				description: 'view - string',
				type: 'string',
				default: '',
			},
			{
				name: 'workspaceId',
				displayName: 'workspaceId',
				description: 'workspaceId - string',
				type: 'string',
				default: '',
			},
			{
				name: 'zipSingleFileOutput',
				displayName: 'zipSingleFileOutput',
				description: 'zipSingleFileOutput - boolean',
				type: 'boolean',
				default: false,
			},
		],
	},
	{
		displayName: 'JSON Object',
		name: 'jsonObject2-json(body)',
		description: 'jsonObject - json',
		type: 'json',
		default: '',
		typeOptions: {
			alwaysOpenEditWindow: true,
		},
		displayOptions: {
			show: {
				resource: [
					'Document',
				],
				operation: [
					'POST /documents/d/{did}/{wv}/{wvid}/e/{eid}/export',
				],
				jsonParameters: [
					true,
				],
				jsonContentType: [
					'application/vnd.onshape.v2+json;charset=UTF-8;qs=0.2',
				],
			},
		},
	},
];
